[package]
name = "ndlrand"
version = "0.1.0"
authors = ["sapessi <stefano.buliani@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"

[dev-dependencies]
kolmogorov_smirnov = "1.1.0"
